/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/": {
    /** Get information about the host */
    get: operations["HelloWorld"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    base_response: {
      /** @description message returned by server side if there is any */
      message?: string;
    };
    module: {
      /** @description zima-chat */
      name?: string;
      /** @description Zima Chat */
      title?: string;
      /** @description module version */
      version?: string;
    };
  };
  responses: {
    /** @description OK */
    response_ok: {
      content: {
        "application/json": components["schemas"]["base_response"];
      };
    };
    /** @description Conflict */
    response_conflict: {
      content: {
        "application/json": components["schemas"]["base_response"];
      };
    };
    /** @description Internal Server Error */
    response_internal_server_error: {
      content: {
        "application/json": components["schemas"]["base_response"];
      };
    };
    /** @description Not Found */
    response_not_found: {
      content: {
        "application/json": components["schemas"]["base_response"];
      };
    };
    /** @description Bad Request */
    response_bad_request: {
      content: {
        "application/json": components["schemas"]["base_response"];
      };
    };
  };
  parameters: {
    name: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Get information about the host */
  HelloWorld: {
    responses: {
      200: components["responses"]["response_ok"];
      500: components["responses"]["response_internal_server_error"];
    };
  };
}
