openapi: 3.0.3

info:
  title: ZimaOS Status API
  version: v2

servers:
  - url: /v2/status

tags:
  - name: Common methods
    description: |-
      methods for common usage

  - name: Web methods
    description: |-
      methods for web interface (INTERNAL USE ONLY)

  - name: Module Info
    description: |-
      <SchemaDefinition schemaRef="#/components/schemas/module" />
    
x-tagGroups:
  - name: Methods
    tags:
      - Common methods
      - Web methods

  - name: Schemas
    tags:
      - Module Info

security:
  - access_token: []

paths:
  /:
    get:
      summary: Get information about the host
      operationId: HelloWorld
      tags:
        - Common methods
      responses:
        "200":
          $ref: "#/components/responses/response_ok"
        "500":
          $ref: "#/components/responses/response_internal_server_error"
  /usage/cpu:
    get:
      summary: Get CPU usage
      operationId: GetCPUUsage
      parameters:
        - name: start
          in: query
          required: true
          schema:
            type: string
            format: timestamp
          example: "1625101200"
        - name: end
          in: query
          required: true
          schema:
            type: string
            format: timestamp
          example: "1625104800"
      tags:
        - Common methods
      responses:
        "200":
          $ref: "#/components/responses/response_get_cpu_info_ok"
        "500":
          $ref: "#/components/responses/response_internal_server_error"

components:
  securitySchemes:
    access_token:
      type: apiKey
      in: header
      name: Authorization

  parameters:
    name:
      name: name
      in: path
      required: true
      schema:
        type: string
        example: "847d7fde"

  responses:
    response_ok:
      description: OK
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/base_response"
          example:
            message: "OK"
      x-go-name: ResponseOK

    response_conflict:
      description: Conflict
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/base_response"
          example:
            message: "Conflict"

    response_internal_server_error:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/base_response"
          example:
            message: "Internal Server Error"

    response_not_found:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/base_response"
          example:
            message: "Not Found"

    response_bad_request:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/base_response"
          example:
            message: "Bad Request"
    
    response_unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/base_response"
          example:
            message: "Unauthorized"

    response_get_cpu_info_ok:
      description: OK
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/base_response"
              - properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/cpu_info"

  schemas:
    base_response: # Every response should inherit from BaseResponse
      properties:
        message:
          description: message returned by server side if there is any
          type: string

    cpu_info:
      required:
        - timestamp
        - percent
      properties:
        timestamp:
          description: timestamp of the data
          type: string
          format: timestamp
        percent:
          description: CPU usage in percent
          type: number
    
    memory_info:
      properties:
        timestamp:
          description: timestamp of the data
          type: string
          format: timestamp
        percent:
          description: Memory usage in percent
          type: number