import createClient from "openapi-fetch";
import type { paths } from "./openapi"; // generated by openapi-typescript
import useSWR from 'swr'

const client = createClient<paths>({ baseUrl: "/v2/status/" });

async function  getCPUHistoryData(duration: string){
    //duration like `cpu 15`
    const durationMin = Number(duration.split(' ')[1]) || 15;

    const currentTimestamp = Math.floor(new Date().getTime()/1000);
    const OneMinuteAgo = currentTimestamp - (60*durationMin);
    const {
        data, // only present if 2XX response
        error, // only present if 4XX or 5XX response
      } = await client.GET("/history/cpu",{
        params: {
            query: { 
                // / 100
                start: OneMinuteAgo.toString(),
                end: currentTimestamp.toString(),
            },
        }});
      return data?.data|| [];
    
}

const useCPUUsageHistory = (duration: number) => {
    const {data,isLoading,error}= useSWR(`cpu ${duration}`,getCPUHistoryData, {
        refreshInterval: 30000, // 3秒钟
      });
    
    return {
        data,
        isLoading,
        error,
    }
}

async function  getCurrentUsage(){
    const {
        data, // only present if 2XX response
        error, // only present if 4XX or 5XX response
      } = await client.GET("/usage");
      return data?.data;
}

const useUsage = () => {
    const {data,isLoading,error}= useSWR('usage',getCurrentUsage, {
        refreshInterval: 3000, // 3秒钟
      });
    
    return {
        data,
        isLoading,
        error,
    }
}


export {useUsage,useCPUUsageHistory};